export const TYPES = {
  READ_STATE_PRODUCTS_CART: "READ_STATE_PRODUCTS_CART",
  READ_STATE_CART: "READ_STATE_CART",
  ADD_TO_CART: "ADD_TO_CART",
  DECREMENTA: "DECREMENTA",
  REMOVE_ALL_PRODUCTS: "REMOVE_ALL_PRODUCTS",
  CLEAR_CART: "CLEAR_CART",
};
